[project]
name = "easysec"
version = "1.2.0"
description = "Open source security automation for SMEs"
readme = "README.md"
requires-python = ">=3.13"
license = { file = "LICENSE.md" }
dependencies = [
    "typer==0.27.1",
    "ansible==14.3.0",
    "pydantic==2.13.4"
]

[project.scripts]
easysec = "cli.main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["cli"]

[dependency-groups]
dev = [
    "pyinstaller==6.22.0",
    "ordered-set==4.1.0"
]

[tool.uv]
exclude-newer = "P7D"
